# Generated by Django 5.0.6 on 2024-07-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
