# Generated by Django 5.0.6 on 2024-07-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
