# Generated by Django 5.0.6 on 2024-07-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_transaction_transfer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
