# Generated by Django 5.0.6 on 2024-07-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accumulated_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
