# Generated by Django 5.0.6 on 2024-08-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_paychecks"),
    ]

    operations = [
        migrations.AddField(
            model_name="paychecks",
            name="payout_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.account",
            ),
        ),
    ]
