# Generated by Django 5.0.6 on 2024-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_transaction_merchant_phone_number_transaction_tip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paychecks',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('old paycheck', 'Old Paycheck')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('purchase', 'Purchase'), ('wage deposit', 'Wage Deposit')], max_length=12),
        ),
    ]
