# Generated by Django 5.0.6 on 2024-08-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_paychecks_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='include_in_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
