# Generated by Django 5.0.6 on 2024-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("savings", "Savings"),
                    ("checking", "Checking"),
                    ("vacation", "Vacation"),
                    ("retirement", "Retirement"),
                    ("other", "Other"),
                    ("credit card", "Credit Card"),
                ],
                max_length=50,
            ),
        ),
    ]
