# Generated by Django 5.0.6 on 2024-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_account_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="creditcard_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("dankort", "Dankort"),
                    ("american express", "American Express"),
                    ("discover", "Discover"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
