# Generated by Django 5.1.4 on 2024-12-15 11:13

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_account_creditcard_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paychecks",
            name="paystub",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=main.models.user_directory_path_paystub,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="paychecks",
            name="work_hour_report",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=main.models.user_directory_path_whr,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
