# Generated by Django 5.1.4 on 2024-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_paychecks_paystub_paychecks_work_hour_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paychecks",
            name="paystub",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="paychecks",
            name="work_hour_report",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
