# Generated by Django 5.1.4 on 2024-12-20 22:04

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_alter_paychecks_paystub_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paychecks",
            name="paystub",
            field=models.FileField(
                blank=True, null=True, upload_to=main.models.user_directory_path_paystub
            ),
        ),
        migrations.AlterField(
            model_name="paychecks",
            name="work_hour_report",
            field=models.FileField(
                blank=True, null=True, upload_to=main.models.user_directory_path_whr
            ),
        ),
    ]
