# Generated by Django 5.1.4 on 2024-12-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_alter_paychecks_paystub_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paychecks",
            name="paystub_original_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paychecks",
            name="work_hour_report_original_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
