# Generated by Django 5.1.4 on 2025-02-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_openbankingrequisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbankingrequisition',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
