# Generated by Django 5.1.4 on 2025-02-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_openbankingaccount_openbankingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbankingtransaction',
            name='entry_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
