# Generated by Django 5.1.4 on 2025-02-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_openbankingtransaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openbankingtransaction',
            name='name',
        ),
    ]
