# Generated by Django 5.1.4 on 2025-02-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_openbankingtransaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbankingaccount',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
