# Generated by Django 5.1.4 on 2025-02-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_openbankingaccount_isfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbankingtransaction',
            name='include_in_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
