# Generated by Django 5.1.4 on 2025-02-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_openbankingtransaction_include_in_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='openbankingrequisition',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
