# Generated by Django 5.1.4 on 2025-02-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_openbankingrequisition_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openbankingrequisition',
            name='expires_at',
        ),
    ]
