# Generated by Django 5.1.4 on 2025-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_remove_openbankingrequisition_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openbankingtransaction",
            name="transaction_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="openbankingtransaction",
            constraint=models.UniqueConstraint(
                fields=("transaction_id", "account"),
                name="unique_transaction_id_per_account",
            ),
        ),
    ]
