# Generated by Django 5.1.4 on 2025-02-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0037_alter_openbankingtransaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paychecks',
            name='payout_account',
        ),
        migrations.AddField(
            model_name='paychecks',
            name='payout_account_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paychecks',
            name='payout_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
