# Generated by Django 5.1.4 on 2025-02-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_paychecks_payout_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecks',
            name='register_payout_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
