name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} <<'EOF'
            cd /home/django
            rm -rf FinanceTracker
            git clone https://github.com/Tovborg/FinanceTracker.git
            cd /home/django/FinanceTracker
            
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          
            cat <<EOT > .env
            DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
            EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
            EOT
          
            source venv/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput
          
            sudo systemctl restart gunicorn
            sudo nginx -t && sudo systemctl restart nginx
          EOF
